def test_model(): ...
def test_trainer(): ...
def test_pretrain_recipe(): ...
def test_pretrain_performance_optimizations(): ...
def test_finetune_recipe(): ...
def test_finetune_performance_optimizations(): ...
