# #### tests needed #### #
# config loads properly
# model instantiates correctly
# model conversion (to, from)
# state_dict mapped correctly
# inference (logits only. nemo_model.predict_step() == hf_model.predict())


def test_llama32_config(): ...
def test_llama32_config_1B(): ...
def test_llama32_model_1B(): ...
def test_llama32_config_3B(): ...
def test_llama32_model_3B(): ...
def test_hfllamaimporter(): ...
