[base]
description = """
a
multiline
persona
description
"""

[rules]

[rules.one]
rule = """
rule one
"""

[rules.two]
rule = """
rule two
"""

[body]
text = """
a
multiline
body
of
text
"""

[tools]

[tools.one]
tool = """
tool one
"""

[tools.two]
tool = """
tool two
"""

[answer]
format = {"tool_name": "ToolName"}